### ISSUE TITLE
Error when executing on an empty repository

### ISSUE THREAD

**Issue by depsir** [optionfactory/digit#1]
When executing digit on an empty repository it states:
`fatal: your current branch 'master' does not have any commits yet`

How to reproduce:
- mkdir test
- cd test
- git init
- digit .

Tried with the windows binary

**Comment by EdMcBane** [comment]
Good catch @depsir 

Looks like "git log" fails with the same exit code (128) when run on:
- a new repo (initialized but empty)
- an empty folder (not a repo)

Fixed in 1.1

**Comment by EdMcBane** [comment]
Released 1.1
