### ISSUE TITLE
Crash when in detached head state

### ISSUE THREAD

**Issue by depsir** [optionfactory/digit#2]
When I try to checkout a commit that would cause a detached head state, digit crashes with this error

```
2016/07/27 17:12:25 executing &{git.exe [git -Ctestdigit symbolic-ref --short HEAD] []  <nil> 0xc04206c138 0xc04206c128 [] <nil> 0xc0421dee10 exit status 128 <nil> <nil> true [0xc04206c140 0xc04206c138 0xc04206c128] [0xc04206c128 0xc04206c138 0xc04206c140] [0xc04206c120 0xc04206c130] [] 0xc042250960 <nil>} got exit status 128, [fatal: ref HEAD is not a symbolic ref]
```

I am using the windows binary release

**Comment by EdMcBane** [comment]
Thanks for the report @depsir

Looks like "git symbolic-ref" returns:
- 128 when its argument is not a symbolic ref, even though the docs say it should return 1
- 129 when another error occurs, even though the docs say it should return 128

```
git symbolic-ref will exit with status 0 if the contents of the
symbolic ref were printed correctly, with status 1 if the requested
name is not a symbolic ref, or 128 if another error occurs.
```

Worked around it in 1.1.
